version: '3.8'

services:
  pgvector-DB:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sreenadh666
      POSTGRES_DB: postgres
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

