version: '3.8'

services:
  pgvector-DB:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sreenadh666
      POSTGRES_DB: postgres
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "80:80"
    env_file:
      - ./backend/.env
    depends_on:
      - pgvector-DB
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:sreenadh666@pgvector-DB:5432/postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

